name: English Comedy Brussels
markdown: kramdown
# pygments: false
# highlighter: rouge
url: www.englishcomedybrussels.com
baseurl: ""

# permalink: /:title
# permalink: /:month-:day-:year/:title.html
permalink: /:year-:month-:day/:title.html

paginate: 5

gems: [jekyll-paginate]

exclude: ["node_modules", "gulpfile.js", "package.json", ".sass-cache"]


# removes added IDs to heading tags:
#     ### SOMETHING => <h3 id"something">SOMETHING</h3> 
kramdown:
  auto_ids: false